### ISSUE TITLE
Get first and last name from oauth provider and send to user service

### ISSUE THREAD

**Issue by ASankaran** [HackIllinois/api-auth#19]
- [ ] Get the first and last name from oauth provider, splitting on the first space if need to separate the two
- [ ] Store the `FirstName` and `LastName` fields in the `UserInfo` struct that gets sent to the oauth service

**Comment by PradyumnaShome** [comment]
@ASankaran Do we need to embed `FirstName` and `LastName` into the JWT in `MakeToken`? I'm not planning to change it, unless you say otherwise.

**Comment by PradyumnaShome** [comment]
I've made most of the required changes to api-auth, api-user, and api-mail. Let me know if `MakeToken` should use the two real names.

**Comment by PradyumnaShome** [comment]
At which part of the API do we do the split of the name? Right now, I've been able to get a name from GitHub, but I'm not sure whether we should have `GetFirstName` and `GetLastName` methods in the OAuth service or in api-user.

**Comment by ASankaran** [comment]
Lets have `GetFirstName` and `GetLastName` methods in the OAuth service since some future OAuth providers, including Linkedin, split the first and last name in their api.
