### ISSUE TITLE
Add Linkedin as an oauth provider

### ISSUE THREAD

**Issue by ASankaran** [HackIllinois/api-auth#35]
- [x] Add Linkedin as an oauth provider
    - [x] Add a `linkedin_service.go` file mirroring the style of the `github_service.go` file
    - [x] Add `linkedin` to the switch cases in `oauth_service.go`

**Comment by PradyumnaShome** [comment]
Is Google OAuth different from LinkedIn / GitHub?

**Comment by ASankaran** [comment]
Yes they are all different OAuth providers. We want users to be able to login with any of the three provider, however we end up disabling some of the providers during our deployment.

**Comment by ASankaran** [comment]
Adding OAuth for each provider should be the same since they are following the same specification. But I did observe slight differences in the strictness of the `url_redirect` parameter between GitHub and Google.
